name: Client Side Tools and Coverage

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      

      - name: Setup Scala and sbt
        run: |
            echo "Installing Scala and sbt..."
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
            wget www.scala-lang.org/files/archive/scala-2.13.6.deb
            sudo dpkg -i scala-2.13.6.deb
            echo "SCALA_HOME=/usr/share/scala" >> $GITHUB_ENV
            echo "/usr/share/scala/bin" >> $GITHUB_PATH
            echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
            echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
            sudo apt-get update
            sudo apt-get install sbt


      - name: Generate coverage report
        run: |
         sbt clean compile jacoco


      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r /home/runner/work/sample-java-sbt-with-cov/sample-java-sbt-with-cov/target/scala-2.13/jacoco/report/jacoco.xml